edge-case: clusters_service public methods didn't exist in private methods
internal/controllers/cluster/cluster_reconciler_function.go:1: : # github.com/osac-project/osac/fulfillment-service/internal/controllers/cluster [github.com/osac-project/osac/fulfillment-service/internal/controllers/cluster.test]
internal/controllers/cluster/cluster_reconciler_function_test.go:894:27: cannot use clustersClient (variable of type *MockClustersClient) as privatev1.ClustersClient value in structliteral: *MockClustersClient does not implement privatev1.ClustersClient (missing method GetKubeconfig)